### ISSUE TITLE
http://codeaweso.me/2015/04/mapping-salesforce-object-fields-to-drupal-taxonomy-terms/

### ISSUE THREAD

**Issue by Jumoke** [MikeChristianson/MikeChristianson.github.io#2]
Hey  I am looking your function get_drupal_field_name() 
Where is this function that is being called?

**Comment by MikeChristianson** [comment]
@Jumoke You're right, it's missing! 

Unfortunately, I no longer have access to the original codebase so I can't get it for you. 

If you use a debugger, or use print statements, to inspect `$field_map`, you may be able to come up with your own version of `get_drupal_field_name()`. 

Good luck!

**Comment by Jumoke** [comment]
//In case it helps someone, use this
function get_drupal_field_info($field_map) {
  $drupal_field = $fieldmap['drupal_field']['fieldmap_value'];
  return field_info_field($drupal_field);
}

**Comment by MikeChristianson** [comment]
Thanks
